### ISSUE TITLE
PreparedStatement Inserts

### ISSUE THREAD

**Issue by jamesoates88** [PatPeter/SQLibrary#10]
Insert should be able to accept a PreparedStatement rather than require a query string.

Additionally it would be nice to have an insertOne method that could be used to insert a single record and return the insert id on success or 0 on failure.

**Comment by PatPeter** [comment]
The insert() method returns an ArrayList of insert ids, so you'd just have to use get(0). I'll look into adding an insert() method that accepts a PreparedStatement.
