### ISSUE TITLE
Incorrect blank password handling

### ISSUE THREAD

**Issue by gdude2002** [PatPeter/SQLibrary#11]
This particular issue makes it impossible for me to use any plugin that uses SQLibrary for data storage.

I have a local-access-only MySQL server on a machine only I have access to. I've set it up with a user that has no password, which handles most of the databases for Minecraft.

However, [this line](https://github.com/PatPeter/SQLibrary/blob/master/lib/PatPeter/SQLibrary/Delegates/HostnameDatabaseImpl.java#L64) makes it impossible for me to use this user for access as your plugin incorrectly doesn't allow blank passwords.

Don't believe me?

MySQL: `To enable the user to connect with no password [...] include no IDENTIFIED BY clause`
http://dev.mysql.com/doc/refman/5.0/en/create-user.html

FrontBase: `FrontBase creates a user named _SYSTEM with no password` (implies others can be created that way too)
http://www.studiotips.net/docs/tips_sql/frontbase/all.html

Informix: Syntax tree doesn't appear to need a password
http://publib.boulder.ibm.com/infocenter/idshelp/v117/index.jsp?topic=%2Fcom.ibm.sqls.doc%2Fids_sqs_1821.htm

Ingres: Null authentication method (however, this may just ignore the user/password altogether)
http://community.actian.com/wiki/Remove_The_Need_For_Operating_System_User_and_Password#Example_Unix_shell_script_to_set_enable_the_null_security_mechanism_in_the_GCN

MSSQL: sa account is a blank password by default
http://support.microsoft.com/kb/322336

Mongo: No users by default; users can be added and there are tickets specifying they can use blank passwords.
https://jira.mongodb.org/browse/SERVER-3003

Oracle: Blank passwords are possible; though you still have to specify them.
http://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:280615845330

So.. Can we have support for this, please?

**Comment by PatPeter** [comment]
I've fixed this issue locally and I can release 4.3 in a few weeks.

**Comment by PatPeter** [comment]
I also allowed blank usernames.
