### ISSUE TITLE
Explain the magic behind this please.

### ISSUE THREAD

**Issue by Xaymar** [PatPeter/SQLibrary#12]
TL;DR: How does this work without using the SQLite JDBC driver?

I've been reading through the code for a few hours now, and still am not able to figure out why or how this works.
SQLibrary is somehow able to use SQLite JDBC without it being installed or having any changes to the classpath. How are you doing this?

Also there is an mistake on L113 and L115 of SQLite.java, that should probably have been SQLite instead of H2.

**Comment by PatPeter** [comment]
The mistake as been fixed, thank you.

Last I recall the JDBC connector for SQLite is built into Bukkit. I know that Bukkit has to pull the connectors for H2, MySQL, and PostgreSQL into the lib folder in the root of your server.
