### ISSUE TITLE
Support for spout server

### ISSUE THREAD

**Issue by ChristopherLMiller** [PatPeter/SQLibrary#13]
Since you split this off to a plugin could you please add spout support.  since you do so little in the plugin itself it would be a piece of cake to add support.  I can submit code to you to do it if you would like.

**Comment by PatPeter** [comment]
Sure, if you want to fork it I'd be more than happy to pull it and build it.

**Comment by ChristopherLMiller** [comment]
I'd be happy to do that.  Not really sure how though but I'll figure it out

**Comment by PatPeter** [comment]
Well, are there any code changes, or do I just compile it with a dependency on Spout?

**Comment by ChristopherLMiller** [comment]
I made a pull request with the code needed to make it work with spout.  Basically just need a new main plugin class, a properties.yml in place of plugin.yml, and dependency in pom for spout.

**Comment by PatPeter** [comment]
Do you know where Spout's Maven repository is? This repository (http://nexus.spout.org/content/groups/public/) does not work. If it wasn't forbidden, I could see where its API jar is, because the jar based on their pom.xml (http://nexus.spout.org/content/groups/public/org/spout/spoutapi-dev-SNAPSHOT.jar) is not on that server.

**Comment by ChristopherLMiller** [comment]
https://oss.sonatype.org/content/groups/public/org/spout/spout-api/1.0.0-SNAPSHOT/ that seems to be the new maven repo.

**Comment by PatPeter** [comment]
Could you please verify that SQLibrary works on Spout?

**Comment by ChristopherLMiller** [comment]
Sent a new pull request that fixes it.  I goofed and didn't even notice it.
