### ISSUE TITLE
Substring throws Exception

### ISSUE THREAD

**Issue by robxu9** [PatPeter/SQLibrary#2]
In Database, the getStatement function can throw an exception if the trimmed query is not of the length expected.
You need to check the size before substringing.

**Comment by PatPeter** [comment]
I read this issue when you first submitted it and I believe I fixed it in a commit that has not been pushed. I'll check when I have the free time to code.

**Comment by robxu9** [comment]
I fixed it in https://github.com/Minequest/Minequest-Reloaded-Core and also added an H2 version of the library. You can check there if you want.

**Comment by PatPeter** [comment]
... how did I not reply to this? I have a clear recollection of replying to you.

Anyway, could you do me a huge favor and pull request your changes?

https://github.com/PatPeter/SQLibrary/pulls

I'm about to make many edits to the library and do not want them to conflict with your changes (last I worked on this was March).

**Comment by robxu9** [comment]
Hm, push your changes first. I can always adapt them easily.

**Comment by PatPeter** [comment]
It only took me 6 months, but I finally fixed this issue (finally).

Feel free to push your changes at anytime. I would love that H2 driver.
