### ISSUE TITLE
isTable() always returns true

### ISSUE THREAD

**Issue by theknet** [PatPeter/SQLibrary#4]
Only tested with SQLite but it always returns true.

To fix it I changed:

md.getTables(null, null, table, null);

to

ResultSet rs = md.getTables(null, null, table, null);
if(rs.next())
    return true;
else
    return false;

**Comment by joshuataylor** [comment]
Found this as well, if you wanted to add a pull request this can be fixed, otherwise I can make one if you want, @thekris1234

**Comment by PatPeter** [comment]
Sorry guys, that's what the algorithm was previously:

https://github.com/PatPeter/SQLibrary/blob/bad9dfe17741dd741edb23d0332d2cac6d8dc9fb/lib/PatPeter/SQLibrary/SQLite.java

I must've read the method wrong during a review and changed it, don't remember why though.

A pull request isn't necessary, I'll change that and try releasing 4.1 next weekend. Until then hotfix it yourselves.

**Comment by PatPeter** [comment]
This issue has been fixed in 4.1 and added to BukkitDev. However, I cannot push 4.1 to GitHub yet due to an error I am diagnosing.
