### ISSUE TITLE
LastInsertId

### ISSUE THREAD

**Issue by jamesoates88** [PatPeter/SQLibrary#5]
How do you get the last insert id?

It would be handy it there was some documentation and usage examples.

**Comment by PatPeter** [comment]
I could swear that I used this functionality from one of my previous projects, but it seems as though the library does not currently support it. I'll add it onto the 4.1 to-do.

**Comment by jamesoates88** [comment]
Thanks that would be good. I don't suppose you know a work around until then?

P.s. Sorry for using Issues, I couldn't work out how to message you directly.

**Comment by PatPeter** [comment]
No, thank you for using issues! That's the most proper way of contacting me in regards to a bug or feature request. The workaround would be:

long key = 0;
PreparedStatement ps = sql.getConnection().prepareStatement("INSERT ...", Statement.RETURN_GENERATED_KEYS);
ps.executeUpdate();
ResultSet keys = ps.getGeneratedKeys();
if (keys.next())
    key = keys.getLong(1);

Where sql is your connection variable.

**Comment by PatPeter** [comment]
This issue has been fixed in 4.1 and added to BukkitDev. However, I cannot push 4.1 to GitHub yet due to an error I am diagnosing.
