### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [PatPeter/SQLibrary#8]
When I attempt to run my server with my plugin the plugin crashes giving the error: "NoClassDefFoundError: lib/PatPeter/SQLibrary/Database" 

I can't anything wrong in my setup or code, could it be a bug?

**Comment by DevonCWoodcomb** [comment]
What plugin? Do you have the sql library jar file in your plugins foldeR?

**Comment by ghost** [comment]
Sorry, I forgot about this thread. I no longer need it. Thanks

**Comment by PatPeter** [comment]
Please make sure to use the SQLibrary.jar, thanks.
